### ISSUE TITLE
PatternMatching should work with Action

### ISSUE THREAD

**Issue by MovGP0** [Patrickkk/FunctionalSharp#13]
`FunctionalSharp.PatternMatching` should work with `Action` instead of `Action<T>` too: 

    value.Match()
        .With(v => v == "foo", DoSomething())
        .Else(DoSomethingElse()); 

instead of: 

     var iDoNotNeedThis = value.Match()
          .With(v => v == "foo", v => { DoSomething(); return 0; })
          .Else(v => { DoSomethingElse(); return 0; });

**Comment by Patrickkk** [comment]
I will check this soon. It will probably seperate set of classes simmilar to 

    PatternMatch<T, TResult>

**Comment by MovGP0** [comment]
Bart De Met has something that works that way: 

https://www.nuget.org/packages/FunctionalSwitch/

**Comment by Patrickkk** [comment]
This feature should be available in the latest version
