### ISSUE TITLE
Option-Types should work with non-nullables (structs)

### ISSUE THREAD

**Issue by MovGP0** [Patrickkk/FunctionalSharp#14]
I regularily have the case that I wast to use the option type instead of nullables because of the added savety. unfortunately it is rather cruel to cast otructure types to a nullable before making them an option type and then unpacking them. 

instead of: 

    var optionalYear = year == 0 ? new None<DateTime?> : ((DateTime?)new DateTime(year,1,1)).ToOption(); 
    var unpackedYear = optionalYear.Match(y => y.HasValue ? y.Value.Year : DateTime.MinValue.Year, DateTime.MinValue.Year); 

i want to simply: 

    var optionalYear = year == 0 ? new None<DateTime> : (new DateTime(year,1,1)).ToOption(); 
    var unpackedYear = optionalYear.Match(y => y.Year, DateTime.MinValue.Year); 

which is much simpler to use.

**Comment by Patrickkk** [comment]
What you are describing in the last example is already possible. only you are missing  ```()``` after ```new  None<DateTime>``` I added a test in the options.test with your second example.

**Comment by Patrickkk** [comment]
Apparantly it does not work. reopening.

**Comment by Patrickkk** [comment]
removed the limitation on Optiontypes to allow non nullable types. should be in the next release.
