### ISSUE TITLE
PatternMatchExtensions should work with null values

### ISSUE THREAD

**Issue by MovGP0** [Patrickkk/FunctionalSharp#15]
I like to match a value against null and convert it to an option type. 

    var item = selectedItem.Match()
        .With(si => string.IsNullOrEmpty(si), new None<Fruit>())
        .With(si => si == "Banana", (new Banana()).ToOption())
        .With(si => si == "Apple", (new Apple()).ToOption())
        .Else(new None<Fruit>()); 

unfortunately this does not work when 'selectedItem' is null in the current version.

**Comment by Patrickkk** [comment]
This has been added to 0.9.2

**Comment by MovGP0** [comment]
thank you! great library btw. I am using it a lot 😃
