### ISSUE TITLE
DiscriminatedUnion not setting tag properly

### ISSUE THREAD

**Issue by MovGP0** [Patrickkk/FunctionalSharp#17]
There seems to be an issue with the tag numbering. Instead of `tag=0; tag=1; tag=2;` it reads `tag=1; tag=1; tag=2;`: 

```csharp
if(value.GetType() == typeof(Type1))
{
	Item1 = (Type1)value; 
	tag = 1; // ERROR: should be 0
}
else if(value.GetType() == typeof(Type2))
{
	Item2 = (Type2)value; 
	tag = 1; 
}
```

**Comment by Patrickkk** [comment]
You are correct. 

Apperently i didn't have a test for the object constructor. I added the tests and it quickly showed as an error.

It should be fixed in version 0.9.3
