### ISSUE TITLE
Have you seen this lib?

### ISSUE THREAD

**Issue by wallymathieu** [Patrickkk/FunctionalSharp#22]
Sort of similar focus:
https://github.com/wallymathieu/with

Is there anything you can use from that lib? Or anything that could inspire other ideas?

**Comment by Patrickkk** [comment]
No i haven't untill now. Ill take a look into it. 
Anything particular that you think would be benefiacial?

**Comment by wallymathieu** [comment]
Well, the easiest thing is to look at the tests and see if there is anything there that you like.
