### ISSUE TITLE
Should be ported to dotnetstandard

### ISSUE THREAD

**Issue by MovGP0** [Patrickkk/FunctionalSharp#23]
FunctionalSharp should be ported to dotnetstandard. `Fody.NullGuard` is not available, so there need to be some additional checks.

**Comment by Patrickkk** [comment]
Yes, i have started work on this, but i intend to keep using nullguard. ill maybe even help the fody nullguard project out porting to dotnetstandard as well

**Comment by MovGP0** [comment]
It seems that NullGuard might get obsolete with C# 8.0. There was a talk with Mads Torgersen presenting compiler supported null checking. 

See also: (Channel9: The future of C#)[https://channel9.msdn.com/events/Build/2017/B8104] (starting at minute 57)

**Comment by Patrickkk** [comment]
yes i saw, actually the most exiting C# feature

**Comment by MovGP0** [comment]
Maybe you can also use `System.Diagnostics.Contracts` for null checking.

**Comment by Patrickkk** [comment]
It is supported by Fody, and I ported everything to .net standard 2.0. Unfortunately multi targeting isn't that easy when using fody, so only .netstandard is now supported.
